version: "3.0"

services:
  mysql:
    image: mysql:8.0
    container_name: lingo-database
    restart: always
    environment:
      MYSQL_DATABASE: lingo-mysql
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
